version: '3.7'
services:

  gate-simulator:
    build: ./gate-simulator
    image: gate-simulator:1.0
    ports:
      - '9999:9999'

  mysql:
    image: mysql:8.0
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass


  postgresql:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass



